#ifndef KLEINERBRAUHELFERCORE_GLOBAL_H
#define KLEINERBRAUHELFERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KLEINERBRAUHELFERCORE_LIBRARY)
#  define LIB_EXPORT Q_DECL_EXPORT
#else
#  define LIB_EXPORT Q_DECL_IMPORT
#endif

#endif // KLEINERBRAUHELFERCORE_GLOBAL_H
