#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
if [ ! -d "$APPIMAGE.config" ] ; then
  mkdir -p "$APPIMAGE.config"
  export XDG_CONFIG_HOME="$APPIMAGE.config"
fi
exec $HERE/usr/bin/kleiner-brauhelfer-2
